### ISSUE TITLE
baseimage.png is hardcoded

### ISSUE THREAD

**Issue by TobiasSeitz** [dmonza/MICodec#1]
I get this error when I run the sample code:
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open 'baseimage.png'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at new WaterMark (/node_modules/micodec/MIEncode.js:185:17)
    at PixerEncode.fileToImage.PixerEncode.processData (/node_modules/micodec/MIEncode.js:44:15)
    at /node_modules/micodec/MIEncode.js:29:9
    at /node_modules/micodec/File.js:31:4
    at Gzip.onEnd (zlib.js:227:5)
    at emitNone (events.js:85:20)
    at Gzip.emit (events.js:179:7)
```
Problem: 'baseimage.png' is hardcoded - it should be possible to use any image, to conceal the message, right?
Affected version/commit 624fbd9

**Comment by dmonza** [comment]
hi Tobias, 

You can use and modify the baseimage.png published with the package. If you leave it blank, the watermark disappear.

I add the issue as a suggestion.

regards
